- hosts: localhost
  gather_facts: no
  vars_files:
    - /opt/keys/aws/keys.yml
  # vars:
  #   some_var:
  tasks:
    # (iam) module: aws_access_ID, aws_secret_ID Supported parameters include: access_key_ids, access_key_state, aws_access_key, aws_secret_key, debug_botocore_endpoint_logs, ec2_url, groups, iam_type, key_count, name, new_name, new_path, password, path, profile, region, security_token, state, trust_policy, trust_policy_filepath, update_password, validate_certs
    - name: Create new IAM user
      iam:
        aws_access_key: "{{ AWS_ACCESS_ID }}"
        aws_secret_key: "{{ AWS_SECRET }}"
        ec2_region: "{{ AWS_REGION }}"
        iam_type: user
        state: present
        name: itenv
        access_key_state: create
      register: itenv

    # - debug: 
    #     var: itenv

    - name: Create group and add the user to it
      iam_group:
        aws_access_key: "{{ AWS_ACCESS_ID }}"
        aws_secret_key: "{{ AWS_SECRET }}"
        ec2_region: "{{ AWS_REGION }}"
        name: itenvgroup
        state: present
        managed_policy:
          - arn:aws:iam::aws:policy/AdministratorAccess
        users:
          - itenv
      register: itenvgroup

    # - debug:
    #     var: itenvgroup
