- hosts: localhost
  gather_facts:yes
  vars_files:
    - keys.yml
  tasks:
    - name: Change instance state By TAG
      ec2:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        ec2_region: "{{ AWS_REGION }}"
        state: running
        # state: stopped
        instance_tag:
          Name: LAB_1
