- hosts: localhost
  gather_facts: no
  vars_files:
    - /opt/keys/aws/keys.yml
  tasks:
    - name: Creating VPC
      ec2_vpc_net:
        aws_access_key: "{{ AWS_ACCESS_ID }}"
        aws_secret_key: "{{ AWS_SECRET }}"
        ec2_region: "{{ AWS_REGION }}"
        cidr_block: 10.10.1.0/24
        name: IT_1
        state: present
        tags:
          vpn: wireguard
        tenancy: default
        # dhcp_opts_id:
      register: IT_1
    - name: Show Info about IT_1
      debug:
        var: IT_1
    - name: VPC info
      ec2_vpc_net_info:
        aws_access_key: "{{ AWS_ACCESS_ID }}"
        aws_secret_key: "{{ AWS_SECRET }}"
        ec2_region: "{{ AWS_REGION }}"
      register: vpc_info
    - name: Show VPC Info from ec2_vpc_net_info module
      debug: 
        var: vpc_info

