- hosts: localhost
  gather_facts: yes
  vars_files:
    - keys.yml
  tasks:
    -name: Delete old key named bm.keypair
      ec2_key:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_KEY }}"
        ec2_region: "{{ AWS_REGION }}"
        name: bm.keypair
        state: absent
    - name: Generate Key with the same name: bm.keypair
      ec2_key:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_KEY }}"
        ec2_region: "{{ AWS_REGION }}"
        name: bm.keypair
      register: keypair
    - debug:
        var: keypair
    - name: Use LineInFile to write the private key to localhost
      lineinfile:
        create: yes
        path: /opt/keys/aws/bm.keypair.pem
        line: "{{ keypair.key.private_key }}"
        mode: 0600
