- hosts: localhost
  gather_facts: yes
  vars_files:
    - keys.yml
  tasks:
    - name: Create ec2 instance
      ec2:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_KEY }}"
        ec2_region: "{{ AWS_REGION }}"
        instance_type: t2.micro
        keypair: bm.keypair
        image:
        assign_public_ip: yes
        vpc_subnet_id: 
        group: LAB_group
        wait: true
        exact_count: 1
        count_tag:
          Name: LAB_1
        instance_tags:
          Name: LAB_1
      register: ec2
    - debug:
        var: ec2
    - name: Add instance to inventory
      add_host:
        hostname: "{{ item.public_ip }}"
        groupname: lab_hosts
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
        ansible_ssh_private_key: "/opt/keys/aws/keypair.pem"
      loop: "{{ ec2.instances }}"

- hosts: lab_hosts
  gather_facts:yes
  remote_user: ec2_user
  tasks:
    -name: wait for SSH
    wait_for_connection:
      delay: 10
      timeout:120
      sleep: 1
      connect_timeout: 5
    -name: Check Ping
      ping:


