- hosts: localhost
  gather_facts: no
  vars_files:
    - /opt/keys/aws/keys.yml
  vars:
   formated_json: '{{ registerdoutput.stdout|from_json}}'
  tasks:
    - name: Gather VPC information
      ec2_vpc_net_info:
        aws_access_key: "{{ AWS_ACCESS_ID }}"
        aws_secret_key: "{{ AWS_SECRET }}"
        ec2_region: "{{ AWS_REGION }}"
        filters:
          "tag:Name": "IT_1"
          # "tag:vpn": "wireguard"
      register: vpcinfo
    - name: Write vpcs IDs in a list
      loop: "{{ vpcinfo | json_query('vpcs[*].id') }}"
      local_action: shell echo "{{ item }}" > /tmp/vpcs-list.txt

    # - name: Write All json to txt
    #   local_action: shell echo "{{ vpcinfo | to_json }}" > /tmp/json-vpcs.txt
