---

- name: Install packages and dependencies
  apt: name={{ item }} update_cache={{ update_apt_cache }} state=present
  with_items:
    - openjdk-8-jdk  # this specific version is needed for Jenkins to run
    - libfontconfig
    - libffi-dev
    - libncurses5-dev

- name: Add the Jenkins public GPG key to the apt repo
  apt_key: url=http://pkg.jenkins-ci.org/debian/jenkins.io.key state=present

- name: Add Jenkins apt repo to the trusted sources list
  apt_repository: repo='deb http://pkg.jenkins.io/debian binary/' update_cache={{ update_apt_cache }} state=present

- name: Install Jenkins server
  apt: name=jenkins state=present

- name: Install additional Python packages
  pip: name={{ item }} state=latest
  with_items:
    - ansible
    - boto
    - boto3
    - flake8
    - passlib
