- hosts: localhost
  gather_facts: no
  vars:
    gcp_cred_file: /opt/keys/gcp/key.json
  vars_files:
    - /opt/keys/gcp/vars
  tasks:
    - name: Get info on instance by state.
      gcp_compute_instance_info:
        zone: "{{ zone }}"
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_type }}"
        service_account_file: "{{ gcp_cred_file }}"
        # filters:
        #   - state: present
        #   - status: TERMINATED
      register: instances
    - debug:
        var: instances
    - name: delete instance
      gcp_compute_instance:
        name: "{{ instances.resources[0].name }}"
        zone: "{{ zone }}"
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_type }}"
        service_account_file: "{{ gcp_cred_file }}"
        state: absent
    - name: remove IP from inventory hosts file
      lineinfile:
        path: /etc/ansible/hosts
        regexp: "{{ instances.resources[0].networkInterfaces[0].accessConfigs[0].natIP }}"
        backup: yes
        state: absent
    - name: remove IP from known hosts
      lineinfile:
        # path: "/home/{{lookup('env','USER')}}/.ssh/known_hosts"
        path: ~/.ssh/known_hosts
        regexp: "{{ instances.resources[0].networkInterfaces[0].accessConfigs[0].natIP }}"
        backup: yes
        state: absent
    # - name: remove host-name from known hosts
    #   lineinfile:
    #     # path: "/home/{{lookup('env','USER')}}/.ssh/known_hosts"
    #     path: ~/.ssh/known_hosts
    #     regexp: "{{ instances.resources[0].networkInterfaces[0].accessConfigs[0].natIP }}"
    #     backup: yes
    #     state: absent

    # - name: remove IP from Hosts list
    #   # for this i need to set tags and use variables damn, and use separate files and folders per projects.
    #   ini_file:
    #     allow_no_value: yes
    #     path: /etc/ansible/hosts
    #     option: "{{ item.option }}"
    #     section: null
    #     state: absent
    #     no_extra_spaces: yes
    #   with_items:
    #     - { option: "{{ instances.resources[0].networkInterfaces[0].accessConfigs[0].natIP }}" }
    #     # - { section: null, option: "" }
