- hosts: localhost
  gather_facts: no
  vars:
    gcp_cred_file: /opt/keys/gcp/key.json
  vars_files:
    - /opt/keys/gcp/vars.delete.instance
  tasks:
    - name: Get info on instance by state.
      gcp_compute_instance_info:
        zone: "{{ zone }}"
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_type }}"
        service_account_file: "{{ gcp_cred_file }}"
        # filters:
        #   - state: stopped
      register: instances
    - debug:
        var: instances
    - debug: 
        msg: " the fak {{ instances.resources[0].networkInterfaces[0].accessConfigs[0].natIP }}"
